[tool.poetry]
name = "jaclang"
version = "0.6.0"
description = "Jaclang is a unique and powerful programming language that runs on top of Python, offering an unprecedented level of intelligence and intuitive understanding."
authors = ["Jason Mars <jason@jaseci.org>"]
license = "MIT"
readme = "README.md"
keywords = ["jaclang", "programming-language", "machine-learning", "artificial-intelligence"]
repository = "https://github.com/Jaseci-Labs/jaclang"
homepage = "https://jaseci.org"
documentation = "https://jac-lang.org"

[tool.poetry.dependencies]
python = "^3.12.0"

[tool.poetry.dev-dependencies]
pytest = "^8.2.1"

[tool.poetry.scripts]
jac = "jaclang.cli.cli:start_cli"

[tool.poetry.extras]
llm = ["mtllm"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"