site_name: The Jac Programming Language
site_url: https://jac-lang.org
nav:
    - ~$: 'index.md'
    - ~/why$: 'why.md'
    - ~/tour$: 'tour.md'
    - ~/example$: 'example.md'
    - ~/book$: 'book.md'
    - ~/blog$: 'blog.md'
    - ~/github$: https://github.com/Jaseci-Labs/jaclang

theme:
    name: 'material'
    palette:
        primary: 'brown'
        accent: 'orange'
    font:
        text: 'Short Stack'
        code: 'Roboto Mono'
    features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: 'autumn'
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.', '../../examples']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
copyright: Copyright &copy; 2023 - 20XX Jac Hackers Everwhere

plugins:
  - search
  - open-in-new-tab