name: VSCE Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          cd support/vscode_ext/jac/
          npm ci
          npm run vsce-package
          npm install --global @vscode/vsce
          vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
